# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/Finance-Bitcoin/project>
	:runtime-requirement [ :on "perl 5.010000"^^:CpanId ];
	:runtime-requirement [ :on "Moo"^^:CpanId ];
	:runtime-requirement [ :on "JSON::RPC::Legacy::Client 0.93"^^:CpanId ];
	.
